### ISSUE TITLE
^add_enum_values with a hash should(?) use values of the hash

### ISSUE THREAD

**Issue by Altai-man** [Kaiepi/p6-Type-EnumHOW#1]
Thanks for your awesome module!

My question is: what is the purpose of `add_enum_values` accepting a Hash if hash values are not used as enum values, but instead a warning is produced?

IMHO, a bit more intuitive API would be:
* Accept a List of keys and derive values from element index.
* Accept a Hash with keys and values and use them both as enum keys and values.

However, it seems that only the first point is true, so I had to use:

```
    $new-enum.^add_enum_values(%symbols.sort(*.value).map(*.key));
```
instead of just
```
    $new-enum.^add_enum_values(%symbols);
```

So is there something I am missing?

**Comment by Kaiepi** [comment]
My bad, I didn't see the notification for this until now.

> My question is: what is the purpose of add_enum_values accepting a Hash if hash values are not used as enum values, but instead a warning is produced?

It should produce a warning, but still go ahead with making the enum anyway (it doesn't look like I remembered to unit test this though...). It's there because `.succ` and `.pred` will not work predictably on enum values if you pass a hash to `^add_enum_values`. If this doesn't matter to you, use `quietly` when calling it.

If no one objects, I'll close this issue after adding documentation of this behaviour to the README and adding unit tests for this.
